# Generated by Django 3.1.2 on 2020-10-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developerverse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
